apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mastodon
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "mastodon-5thfloor"
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "gce"
spec:
  tls:
  - hosts:
    - mastodon.5thfloor.co.jp
    secretName: mastodon-tls
  rules:
  - host: mastodon.5thfloor.co.jp
    http:
      paths:
      - path: /*
        backend:
          serviceName: frontend
          servicePort: 80