apiVersion: batch/v1
kind: Job
metadata:
  name: pre-deployment-migration-job
spec:
  template:
    spec:
      containers:
      - name: web
        image: gcr.io/the5thfloorinc/mastodon:production
        imagePullPolicy: Always
        env:
        - name: SKIP_POST_DEPLOYMENT_MIGRATIONS
          value: "true"
        envFrom:
        - configMapRef:
            name: env-production
        # resources:
        #   requests:
        #     cpu: "80m"
        volumeMounts:
        - name: mastodon-disk-system
          mountPath: /mastodon/public/system
        command: ["bundle", "exec", "rails", "db:migrate"]
      volumes:
      - name: mastodon-disk-system
        emptyDir: {}
      restartPolicy: Never
  backoffLimit: 1
